ALTER TABLE restore_runs
    ADD COLUMN IF NOT EXISTS target_vm_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS phase TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS cleanup_errors JSONB NOT NULL DEFAULT '[]'::jsonb;
