ALTER TABLE discovery_scans
    ADD COLUMN IF NOT EXISTS phase TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS probe_total INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS probe_completed INTEGER NOT NULL DEFAULT 0;
