ALTER TABLE restore_runs
    ADD COLUMN IF NOT EXISTS target_server_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS target_cluster_id TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS target_cluster_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS target_disk_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS target_domain_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS transfer_id TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS transferred_bytes BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_bytes BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bytes_per_second BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_progress_at TIMESTAMPTZ;

ALTER TABLE verify_runs
    ADD COLUMN IF NOT EXISTS phase TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS transferred_bytes BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_bytes BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bytes_per_second BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_progress_at TIMESTAMPTZ;
